name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
        with:
          submodules: true
      - name: Build and test
        run: docker build -t emvcard-builder -f Dockerfile .
      - name: Copy JavaCard build
        run: docker run --rm emvcard-builder cat /tmp/javacard_build.tar.gz >
          javacard_build.tar.gz && tar xvzf javacard_build.tar.gz
      - name: Upload JavaCard build artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3.1.0
        with:
          name: javacard_build
          path: 'javacard_build'
