censor_sensitive_fields: false
configuration_files:
  # Configuration files here have relative path from the caller, not from the settings file
  # If path is not found, default settings (test CAs) will be used
  emv_tags: 'emv_tags.yaml'
  scheme_ca_public_keys: 'scheme_ca_public_keys_test.yaml'
  constants: 'constants.yaml'
terminal:
  use_random: true
  capabilities:
    sda: true
    dda: true
    cda: true
    plaintext_pin: true
    enciphered_pin: true
    terminal_risk_management: true
    issuer_authentication: false
  tvr:
    offline_data_authentication_was_not_performed: false
    sda_failed: false
    icc_data_missing: false
    card_appears_on_terminal_exception_file: false
    dda_failed: false
    cda_failed: false
    icc_and_terminal_have_different_application_versions: false
    expired_application: false
    application_not_yet_effective: false
    requested_service_not_allowed_for_card_product: false
    new_card: false
    cardholder_verification_was_not_successful: false
    unrecognised_cvm: false
    pin_try_limit_exceeded: false
    pin_entry_required_and_pin_pad_not_present_or_not_working: false
    pin_entry_required_pin_pad_present_but_pin_was_not_entered: false
    online_pin_entered: false
    transaction_exceeds_floor_limit: false
    lower_consecutive_offline_limit_exceeded: false
    upper_consecutive_offline_limit_exceeded: false
    transaction_selected_randomly_for_online_processing: false
    merchant_forced_transaction_online: false
    default_tdol_used: false
    issuer_authentication_failed: false
    script_processing_failed_before_final_generate_ac: false
    script_processing_failed_after_final_generate_ac: false
  tsi:
    offline_data_authentication_was_performed: false
    cardholder_verification_was_performed: false
    card_risk_management_was_performed: false
    issuer_authentication_was_performed: false
    terminal_risk_management_was_performed: false
    script_processing_was_performed: false
  terminal_transaction_qualifiers:
    mag_stripe_mode_supported: false
    emv_mode_supported: true
    emv_contact_chip_supported: true
    offline_only_reader: false
    online_pin_supported: false
    signature_supported: true
    offline_data_authentication_for_online_authorizations_supported: true
    online_cryptogram_required: false
    cvm_required: false
    contact_chip_offline_pin_supported: true
    issuer_update_processing_supported: false
    consumer_device_cvm_supported: false
  cryptogram_type: 'AuthorisationRequestCryptogram'
  cryptogram_type_arqc: 'TransactionCertificate'
default_tags:
  '9F1A': '0246'
  '5F2A': 0978
  '9C': '21'
  '9F35': '23'
